### ISSUE TITLE
SocketImplementation add_user_socket

### ISSUE THREAD

**Issue by darthpedroo** [ElBettoo/TrucoBackend#12]
en add_user_socket, estoy pasando mal un *args porque se madna como doble tupla. 
![image](https://github.com/ElBettoo/TrucoBackend/assets/79163424/eb8afefd-6ac0-4e7e-a72a-98cc9936ae34)
esta hardcodeado mientras tanto para que ande bien ( puse el doble [0][0] aproposito)

**Comment by darthpedroo** [comment]
![image](https://github.com/ElBettoo/TrucoBackend/assets/79163424/bb6cb1f4-32d3-42dd-bc89-f920e574c882)

pasa algo parecido con switch_round

**Comment by joacoffernandez** [comment]
PORKY NEVER COOK AGAIN
