### ISSUE TITLE
No se quitan los usuarios de la sala

### ISSUE THREAD

**Issue by Juaniitrox2** [ElBettoo/TrucoBackend#3]
cuando alguien se desconecta no sel e sale de la sala :VVv no sé porq así q hago issueee ndeaaa

**Comment by darthpedroo** [comment]
the divine gods have talked and the code has fixed itself 
![image](https://github.com/ElBettoo/TrucoBackend/assets/79163424/ea80c86f-0856-4b38-95a9-cef0873891bf)
![image](https://github.com/ElBettoo/TrucoBackend/assets/79163424/c08da191-3baa-47bd-b970-e2535631457d)
